Updated topology page.
nuts-foundation/nuts-monitor pull request #55
Opened 2023-05-02 11:36 UTC by woutslakhorst

- updated graphics
- mouse over action giving additional info on a node
- info on node: NodeDID, certificate info, NutsComm address, tx count, software info and more

<img width="1203" alt="Screenshot 2023-05-02 at 13 29 00" src="https://user-images.githubusercontent.com/703298/235655378-b3d18213-cf2d-4544-a912-8337b0c5d812.png">

2023-05-06 04:05 UTC, reinkrul requested changes
I don't have an opinion on the javascript part of things

2023-05-06 04:05 UTC, reinkrul commented on client/topology.go
> +							conn, err := tls.Dial("tcp", nutsComm, &tls.Config{InsecureSkipVerify: true})
what is the time-out?

2023-05-06 04:05 UTC, reinkrul commented on client/topology.go
> +				document, err := ts.HTTPClient.DIDDocument(ctx, *peer.NodeDID)
You might want to cache this, since this is an N+1 type query?
(same for the TLS dial)

2023-05-09 07:16 UTC, woutslakhorst commented on client/topology.go
> +							conn, err := tls.Dial("tcp", nutsComm, &tls.Config{InsecureSkipVerify: true})
changed it to 2 second.

2023-05-09 07:18 UTC, reinkrul approved these changes

2023-05-10 13:25 UTC, merged